version: "3"


services:
  threemegawatt:
    build:
      context: .

    ports:
      - "8000:8000"
    volumes:
      - ./threemegawatt:/threemegawatt
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"