# Generated by Django 2.2.3 on 2019-07-30 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy_expected', models.FloatField()),
                ('energy_observed', models.FloatField()),
                ('irradiation_expected', models.FloatField()),
                ('irradiation_observed', models.FloatField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Plant')),
            ],
        ),
    ]
