# Generated by Django 2.2.3 on 2019-07-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
